# config.yaml
# ----
# The arguments for the Main.py program are read from this file.
# ----

methods: ['random', 'max', 'margin', 'entropy']

ET:
  initial_step: 30
  step: 15
  stop: True
  stop_samples: 3000
  random_state: 41

DSH:
  path: "C:\\Users\\34640\\Documents\\Python_VSCode\\TFG_DecisionTree\\nslkdd"
  #path: "C:\\Users\\34640\\Documents\\Python_VSCode\\TFG_DecisionTree\\unswnb15"

DS:
  path: "C:\\Users\\34640\\Documents\\Python_VSCode\\TFG_DecisionTree\\unswnb15_old"
